# Generated by Django 4.1.8 on 2023-04-09 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_userdata_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='phno',
            new_name='PhoneNo',
        ),
    ]
