# Generated by Django 4.1.8 on 2023-04-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_userdata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='PhoneNo',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
