# Generated by Django 4.1.8 on 2023-04-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_userdata_phoneno_alter_userdata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='PhoneNo',
            field=models.CharField(max_length=15),
        ),
    ]
