# Generated by Django 4.1.8 on 2023-04-14 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_userdata_phoneno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admindata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('UserId', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'db_table=',
            },
        ),
        migrations.AlterField(
            model_name='userdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
