# Generated by Django 4.1.8 on 2023-04-14 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_admindata_alter_userdata_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admindata',
            table='admin_data',
        ),
    ]
