# Generated by Django 4.1.8 on 2023-04-14 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_admindata_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admindata',
            name='Name',
        ),
    ]
