# Generated by Django 2.2 on 2023-05-04 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_portfolio'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='portfolio',
            table='portfoliodata',
        ),
    ]
