# Generated by Django 2.2 on 2023-05-06 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20230504_2345'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='portfolio',
            table='portfoliodata;',
        ),
    ]
