# Generated by Django 2.2 on 2023-05-06 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20230506_0943'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='portfolio',
            table='portfoliodata',
        ),
    ]
