# Generated by Django 2.2 on 2023-05-06 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20230506_0955'),
    ]

    operations = [
        migrations.DeleteModel(
            name='portfolio',
        ),
    ]
