# Generated by Django 2.2 on 2023-05-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_delete_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_title', models.CharField(max_length=255)),
                ('portfolio_link', models.TextField()),
                ('portfolio_img', models.ImageField(upload_to='static/portfolio_images/')),
            ],
            options={
                'db_table': 'portfoliodata',
            },
        ),
    ]
